### ISSUE TITLE
Not starting on Raspberry

### ISSUE THREAD

**Issue by dersimn** [holgerimbery/docker_hm2mqtt#3]
```
root@raspberrypi:~ # docker run holgerimbery/docker_hm2mqtt --help
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--help\": executable file not found in $PATH": unknown.
ERRO[0005] error waiting for container: context canceled 
```

**Comment by holgerimbery** [comment]
Hi Simon, 
try „docker run holgerimbery/docker_hm2mqtt“ or „docker run holgerimbery/docker_hm2mqtt hm2mqtt —help“. 
Your syntax was wrong, you can see it here:
„..caused „exec: \“—help\“: executable file not in ...“

The Container is running here as a service on a swarm of 6 Raspberry PI 3 B+.

It seems the issue was a picnic problem :)

**Comment by dersimn** [comment]
Alright.. got it.. because you're using `CMD` instead of `ENTRYPOINT` [here](https://github.com/holgerimbery/docker_hm2mqtt/blob/83bcbe5135cc0fa7a8e4a4e3e839ec5a22f3dc2e/Dockerfile#L20).
